name: Continuous Integration

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.2']
    env:
      CONSTRAINT_ENFORCEMENT_ENABLED: "enabled"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: "Gemfile.lock"
        bundler-cache: true
    - name: Lock bundle
      run: bundle lock --add-platform x86_64-linux

    - name: Run tests
      run: bundle exec rake
